version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gymmanager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gym-net

  db:
    image: mysql:8.0
    container_name: mysql-gym-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gymmanager
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gym-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  gym-net:
    driver: bridge
